### ISSUE TITLE
FMUM导致无法进入世界

### ISSUE THREAD

**Issue by NobodyHere-rrr** [Giant-Salted-Fish/FMUM-1122#1]
FMUM 版本：FMUM 2.0 v0.3.1-alpha-dev-preview - 2023-5-3

崩溃日志如下：
---- Minecraft Crash Report ----
// Lolis deobfuscated this stacktrace using MCP's stable-39 mappings.
// Why did you do that?

Time: 2023-05-13 14:53:49 CST
Description: Ticking memory connection

java.lang.ClassCastException: com.fmum.common.player.PlayerPatch cannot be cast to flaxbeard.cyberware.api.ICyberwareUserData
    at flaxbeard.cyberware.api.CyberwareAPI.getCapabilityOrNull(CyberwareAPI.java:373)
    at flaxbeard.cyberware.common.item.ItemBoneUpgrade.handleJoinWorld(ItemBoneUpgrade.java:77)
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_3861_ItemBoneUpgrade_handleJoinWorld_EntityJoinWorldEvent.invoke(.dynamic)
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
    at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
    at net.minecraft.world.World.spawnEntity(MixinWorldRedstone.java:1209)
    at net.minecraft.world.WorldServer.spawnEntity(WorldServer.java:1058)
    at net.minecraft.server.management.PlayerList.playerLoggedIn(PlayerList.java:377)
    at net.minecraft.server.management.PlayerList.initializeConnectionToPlayer(PlayerList.java:166)
    at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher.completeServerSideConnection(NetworkDispatcher.java:255)
    at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher.access$100(NetworkDispatcher.java:72)
    at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher$1.update(NetworkDispatcher.java:205)
    at net.minecraft.network.NetworkManager.processReceivedPackets(NetworkManager.java:285)
    at net.minecraft.network.NetworkSystem.networkTick(NetworkSystem.java:180)
    at net.minecraft.server.MinecraftServer.updateTimeLightAndEntities(MinecraftServer.java:790)
    at net.minecraft.server.MinecraftServer.tick(MinecraftServer.java:668)
    at net.minecraft.server.integrated.IntegratedServer.tick(IntegratedServer.java:279)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
    at java.lang.Thread.run(Thread.java:748)

看上去像是与[Robotic Parts](https://www.mcmod.cn/class/1616.html)有冲突？

**Comment by Giant-Salted-Fish** [comment]
应该是因为我的 PlayerPatch Capability 的 get 方法默认情况下没做检查，稍后我会解决这个问题。感谢你提交的 Iusse。

**Comment by NobodyHere-rrr** [comment]
> 应该是因为我的 PlayerPatch Capability 的 get 方法默认情况下没做检查，稍后我会解决这个问题。感谢你提交的 Iusse。

额，所以现在在哪里可以下载呢？

**Comment by Giant-Salted-Fish** [comment]
> > 应该是因为我的 PlayerPatch Capability 的 get 方法默认情况下没做检查，稍后我会解决这个问题。感谢你提交的 Iusse。
> 
> 额，所以现在在哪里可以下载呢？

这两天有点事忙，之后会 build 一个小版本发。
